/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author snake
 */
public class ContenedorP2p extends javax.swing.JFrame {

    /**
     * Creates new form ContenedorP2p
     */
    public ContenedorP2p() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        catalogo = new javax.swing.JMenu();
        alumnos = new javax.swing.JMenuItem();
        maestros = new javax.swing.JMenuItem();
        procesos = new javax.swing.JMenu();
        asigalumnos = new javax.swing.JMenuItem();
        asigmastro = new javax.swing.JMenuItem();
        informes = new javax.swing.JMenu();
        sedes = new javax.swing.JMenuItem();
        herramientas = new javax.swing.JMenu();
        ayuda = new javax.swing.JMenu();
        salir = new javax.swing.JMenu();
        salida = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 865, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        catalogo.setText("Catalogos");

        alumnos.setText("Alumnos");
        catalogo.add(alumnos);

        maestros.setText("Maestros");
        maestros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maestrosActionPerformed(evt);
            }
        });
        catalogo.add(maestros);

        jMenuBar1.add(catalogo);

        procesos.setText("Procesos");

        asigalumnos.setText("AsignacionA");
        asigalumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asigalumnosActionPerformed(evt);
            }
        });
        procesos.add(asigalumnos);

        asigmastro.setText("AsignacionM");
        asigmastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asigmastroActionPerformed(evt);
            }
        });
        procesos.add(asigmastro);

        jMenuBar1.add(procesos);

        informes.setText("Informes");

        sedes.setText("Sedes");
        informes.add(sedes);

        jMenuBar1.add(informes);

        herramientas.setText("Herramientas");
        jMenuBar1.add(herramientas);

        ayuda.setText("Ayuda");
        jMenuBar1.add(ayuda);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        salida.setText("OUT");
        salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salidaActionPerformed(evt);
            }
        });
        salir.add(salida);

        jMenuBar1.add(salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed

    }//GEN-LAST:event_salirActionPerformed

    private void maestrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maestrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maestrosActionPerformed

    private void asigalumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asigalumnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asigalumnosActionPerformed

    private void asigmastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asigmastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asigmastroActionPerformed

    private void salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salidaActionPerformed
    dispose();
    }//GEN-LAST:event_salidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContenedorP2p.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContenedorP2p.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContenedorP2p.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContenedorP2p.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContenedorP2p().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alumnos;
    private javax.swing.JMenuItem asigalumnos;
    private javax.swing.JMenuItem asigmastro;
    private javax.swing.JMenu ayuda;
    private javax.swing.JMenu catalogo;
    private javax.swing.JMenu herramientas;
    private javax.swing.JMenu informes;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem maestros;
    private javax.swing.JMenu procesos;
    private javax.swing.JMenuItem salida;
    private javax.swing.JMenu salir;
    private javax.swing.JMenuItem sedes;
    // End of variables declaration//GEN-END:variables
}
